// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpg11dVYSIws4eD5QotKf_3o6ZVirsWrM',
    appId: '1:370943465435:web:2dbe8fe1f0427b0125b9fe',
    messagingSenderId: '370943465435',
    projectId: 'notes-final-300f1',
    authDomain: 'notes-final-300f1.firebaseapp.com',
    storageBucket: 'notes-final-300f1.appspot.com',
    measurementId: 'G-66QXERQ6K0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClEk57OCl4jNDXNdccmJBRAbXkxnOsUWE',
    appId: '1:370943465435:android:8a5e62062286173f25b9fe',
    messagingSenderId: '370943465435',
    projectId: 'notes-final-300f1',
    storageBucket: 'notes-final-300f1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2jvEHOquzEEHncFpE6lHsPrpb0icrsF4',
    appId: '1:370943465435:ios:b5118d652c4f75fa25b9fe',
    messagingSenderId: '370943465435',
    projectId: 'notes-final-300f1',
    storageBucket: 'notes-final-300f1.appspot.com',
    iosBundleId: 'com.example.notesFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2jvEHOquzEEHncFpE6lHsPrpb0icrsF4',
    appId: '1:370943465435:ios:e028f1e412a3454225b9fe',
    messagingSenderId: '370943465435',
    projectId: 'notes-final-300f1',
    storageBucket: 'notes-final-300f1.appspot.com',
    iosBundleId: 'com.example.notesFinal.RunnerTests',
  );
}
